<?php

namespace EnsahBundle\Repository;

/**
 * EmploiTempsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiTempsRepository extends \Doctrine\ORM\EntityRepository
{
}
